stages:
    - build
    - update_helm_chart

variables:
    APP_NAME: nodejs
    IMAGE_TAG: registry.gitlab.com/willie98/node-devops-project/$APP_NAME:$CI_COMMIT_SHORT_SHA


build_image:
  image: docker
  stage: build
  services:
    - docker:dind
  # IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

helm:
  stage: update_helm_chart
  image: ubuntu:22.04
  before_script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
      - mkdir -p /root/.ssh
      - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
        # run ssh-agent
      - eval $(ssh-agent -s)
        # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
      - echo "$SSH_PRIVATE_KEY" | tr -d  | ssh-add -  
      # Git
      - git config --global user.email "mohamedwaleed2912@gmail.com"
      - git config --global user.name "willie98"
      - git clone git@gitlab.com:willie98/node-devops-project.git
      - ls -latr
      
  script:
    # Update Image TAG
     - sed -i "s/nodejs:.*/nodejs:${CI_COMMIT_SHORT_SHA}/g" values.yaml
     - git add values.yaml
     - git commit -am "Update Image"
     - git push